### ISSUE TITLE
CssSyntaxError The `invalid-feedback` class does not exist. with version 1.0

### ISSUE THREAD

**Issue by sezaru** [petalframework/petal_components#141]
I just updated my PetalComponent version to 1.0

After doing the two needed changes (adding the new colors to `tailwind.config.js` and adding the `default.css` import to `app.css` I tried to run my app again, but I get the following error:

```
CssSyntaxError: tailwindcss: /home/sezdocs/projects/rebuilt/marketplace/deps/petal_components/assets/default.css:480:3: The `invalid-feedback` class does not exist. If `invalid-feedback` is a custom class, make sure it is defined within a `@layer` directive.
    at Input.error (/snapshot/tailwindcss/node_modules/postcss/lib/input.js:148:16)
    at AtRule.error (/snapshot/tailwindcss/node_modules/postcss/lib/node.js:60:32)
    at processApply (/snapshot/tailwindcss/lib/lib/expandApplyAtRules.js:376:29)
    at /snapshot/tailwindcss/lib/lib/expandApplyAtRules.js:524:9
    at /snapshot/tailwindcss/lib/processTailwindFeatures.js:55:50
    at Object.Once (/snapshot/tailwindcss/lib/cli/build/plugin.js:251:19)
    at LazyResult.runOnRoot (/snapshot/tailwindcss/node_modules/postcss/lib/lazy-result.js:337:23)
    at LazyResult.runAsync (/snapshot/tailwindcss/node_modules/postcss/lib/lazy-result.js:393:26) {
  reason: 'The `invalid-feedback` class does not exist. If `invalid-feedback` is a custom class, make sure it is defined within a `@layer` directive.',
  file: '/home/sezdocs/projects/rebuilt/marketplace/deps/petal_components/assets/default.css',
  source: '/* Container */\n' +
```

**Comment by mplatts** [comment]
Thanks, taking a look now

**Comment by mplatts** [comment]
Can you try again with v1.0.1 - https://github.com/petalframework/petal_components/releases/tag/v1.0.1

**Comment by sezaru** [comment]
Yep, that fixed it, thanks!
